"""`config/projects.toml` — §10. The single place a stack fact lives in layer D."""

from __future__ import annotations

import tomllib
from collections.abc import Mapping
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from factory.machine import Blocked

__all__ = ["Defaults", "Project", "Registry", "RegistryError", "VaultConfig", "load_registry"]


class RegistryError(Exception):
    """A configuration error the daemon must refuse to start on."""


@dataclass(frozen=True)
class VaultConfig:
    path: Path
    write_allowlist: tuple[str, ...]
    snapshot_exclude: tuple[str, ...]


@dataclass(frozen=True)
class Planning:
    auto: bool
    acceptance_criteria_over: int
    description_chars_over: int


@dataclass(frozen=True)
class RedPhase:
    inconclusive: str
    inconclusive_alarm_pct: int


@dataclass(frozen=True)
class Defaults:
    worktree_subdir: str
    max_attempts: int
    max_total_attempts: int
    disk_min_free_gb: int
    concurrency_per_project: int
    planning: Planning
    redphase: RedPhase
    timeouts_seconds: Mapping[str, int]
    #: §8.7 — per-sandbox egress denials applied to **every** factory sandbox at
    #: creation. `sbx` fixes these at `create`, so this is a creation-time decision
    #: like the template and the static MCP set.
    deny_network: tuple[str, ...] = ()


@dataclass(frozen=True)
class Project:
    name: str
    team: str
    path: Path
    remote: str
    base_branch: str
    stack: str
    template: str
    kits: tuple[str, ...]
    static_mcp: tuple[str, ...]
    build_sandbox: str
    review_sandbox: str
    vault_mount: str
    network_allow: tuple[str, ...]
    env: Mapping[str, str] = field(default_factory=dict)
    requires_clone: bool = False
    #: Credential names that `sbx` puts in the sandbox environment, that this project
    #: has looked at and decided to run with anyway. Every name here is recorded as a
    #: `warn` on every run rather than passing silently; a name *not* here blocks. The
    #: list is per project because the judgement is per project — see
    #: `policy.capability_env_names`.
    acknowledged_env_credentials: tuple[str, ...] = ()

    @property
    def base_ref(self) -> str:
        """Always the remote ref. Never the local branch, and never `main` for these
        two repos, where `main` is generated by CI (§2.2)."""
        return f"origin/{self.base_branch}"

    def worktree_path(self, subdir: str, identifier: str) -> Path:
        return self.path / subdir / identifier


@dataclass(frozen=True)
class Registry:
    vault: VaultConfig
    defaults: Defaults
    projects: Mapping[str, Project]

    def resolve(self, identifier: str) -> Project:
        """§10.2 steps 1 to 3. Zero matches is "not eligible"; two is a config error.

        The distinction matters: an unknown team key is a ticket the factory was never
        meant to see, and a duplicated one is a registry that would silently send two
        teams' work to one repository.
        """
        team = identifier.split("-", 1)[0]
        matches = [p for p in self.projects.values() if p.team == team]
        if len(matches) > 1:
            raise RegistryError(
                f"team {team!r} is claimed by {len(matches)} projects: "
                f"{sorted(p.name for p in matches)}"
            )
        if not matches:
            raise Blocked("unknown-team", f"no project in the registry claims team {team!r}")
        return matches[0]


def _defaults(raw: Mapping[str, Any]) -> Defaults:
    planning_raw = dict(raw.get("planning", {}))
    redphase_raw = dict(raw.get("redphase", {}))
    inconclusive = str(redphase_raw.get("inconclusive", "report"))
    if inconclusive not in {"report", "escalate", "block"}:
        raise RegistryError(
            f"redphase.inconclusive must be report|escalate|block, got {inconclusive!r}"
        )
    return Defaults(
        worktree_subdir=str(raw.get("worktree_subdir", ".factory/worktrees")),
        max_attempts=int(raw.get("max_attempts", 3)),
        max_total_attempts=int(raw.get("max_total_attempts", 5)),
        disk_min_free_gb=int(raw.get("disk_min_free_gb", 20)),
        concurrency_per_project=int(raw.get("concurrency_per_project", 1)),
        planning=Planning(
            auto=bool(planning_raw.get("auto", False)),
            acceptance_criteria_over=int(planning_raw.get("acceptance_criteria_over", 12)),
            description_chars_over=int(planning_raw.get("description_chars_over", 8000)),
        ),
        redphase=RedPhase(
            inconclusive=inconclusive,
            inconclusive_alarm_pct=int(redphase_raw.get("inconclusive_alarm_pct", 30)),
        ),
        timeouts_seconds={str(k): int(v) for k, v in dict(raw.get("timeouts_seconds", {})).items()},
        deny_network=tuple(str(h) for h in raw.get("deny_network", ())),
    )


def _project(name: str, raw: Mapping[str, Any]) -> Project:
    required = ("team", "path", "remote", "base_branch", "stack", "build_sandbox")
    missing = [key for key in required if key not in raw]
    if missing:
        raise RegistryError(f"project {name!r} is missing {missing}")
    if raw["base_branch"] == "main" and name in {"python-harness", "frontend-harness"}:
        raise RegistryError(
            f"project {name!r} names `main` as its base branch, but `main` there is "
            "generated by generate-main.yml and is never a merge target (§2.2)"
        )
    return Project(
        name=name,
        team=str(raw["team"]),
        path=Path(str(raw["path"])),
        remote=str(raw["remote"]),
        base_branch=str(raw["base_branch"]),
        stack=str(raw["stack"]),
        template=str(raw.get("template", "")),
        kits=tuple(str(k) for k in raw.get("kits", ())),
        static_mcp=tuple(str(m) for m in raw.get("static_mcp", ())),
        build_sandbox=str(raw["build_sandbox"]),
        review_sandbox=str(raw.get("review_sandbox", "")),
        vault_mount=str(raw.get("vault_mount", "rw")),
        network_allow=tuple(str(h) for h in raw.get("network_allow", ())),
        env={str(k): str(v) for k, v in dict(raw.get("env", {})).items()},
        requires_clone=bool(raw.get("requires_clone", False)),
        acknowledged_env_credentials=tuple(
            str(n) for n in raw.get("acknowledged_env_credentials", ())
        ),
    )


def load_registry(path: Path) -> Registry:
    """Parse and validate `projects.toml`. Raises rather than defaulting.

    Validation happens at load because §4.5's reasoning applies to the registry too: a
    control plane running on a half-understood configuration looks identical to one
    running correctly, right up until it writes to the wrong repository.
    """
    raw = tomllib.loads(path.read_text(encoding="utf-8"))

    vault_raw = raw.get("vault", {})
    if "path" not in vault_raw:
        raise RegistryError("projects.toml has no [vault] path")
    vault = VaultConfig(
        path=Path(str(vault_raw["path"])),
        write_allowlist=tuple(
            str(g)
            for g in vault_raw.get("write_allowlist", ("Project Learnings/**", "_VAULT_INDEX.md"))
        ),
        snapshot_exclude=tuple(
            str(d) for d in vault_raw.get("snapshot_exclude", (".obsidian", ".git", ".trash"))
        ),
    )

    projects = {name: _project(name, body) for name, body in raw.get("projects", {}).items()}
    if not projects:
        raise RegistryError("projects.toml declares no projects")

    seen: dict[str, str] = {}
    for project in projects.values():
        if project.team in seen:
            raise RegistryError(
                f"team {project.team!r} is claimed by both {seen[project.team]!r} "
                f"and {project.name!r}"
            )
        seen[project.team] = project.name

    return Registry(vault=vault, defaults=_defaults(raw.get("defaults", {})), projects=projects)
