"""Automatic certification prerequisite shared by builders, reviewers and recovery."""

from __future__ import annotations

import json
import time
from functools import partial
from pathlib import Path
from typing import TYPE_CHECKING, Any, cast

from factory import authority
from factory.agent.app_server import AppServerAdapter, read_evidence
from factory.agent_launches import AgentLaunches
from factory.certification import Certifications
from factory.certification_fingerprint import CertificationObserver, FingerprintInputs, observe
from factory.certification_runner import CertificationRunner
from factory.execution import ProjectQueued
from factory.machine import Blocked

if TYPE_CHECKING:
    from factory.sandbox.base import SandboxSpec
    from factory.steps import Context


SETTING_KEYS = ("certification_mode", "certification_config")


def configuration(path: Path, *, writable_roots: tuple[Path, ...]) -> dict[str, Any]:
    try:
        if not path.is_absolute() or any(
            path.resolve().is_relative_to(p.resolve()) for p in writable_roots
        ):
            raise ValueError("certification configuration must be host-owned")
        config = json.loads(read_evidence(path.parent, path.name))
        if not isinstance(config, dict) or set(config) != {
            "binary",
            "source",
            "model",
            "alternate_model",
            "effort",
            "usage_scope",
            "canary_path",
        }:
            raise ValueError("invalid certification configuration fields")
        if not all(isinstance(value, str) and value for value in config.values()):
            raise ValueError("certification fields must be nonempty strings")
        if not Path(config["binary"]).is_absolute() or not Path(config["source"]).is_absolute():
            raise ValueError("native binary and source contract must be absolute")
        if config["usage_scope"] not in {"thread", "connection"}:
            raise ValueError("unknown usage scope")
        canary = Path(config["canary_path"])
        if canary.is_absolute() or ".." in canary.parts:
            raise ValueError("canary must be target-relative")
        return config
    except (OSError, ValueError, KeyError, TypeError) as exc:
        raise Blocked("certification-configuration-invalid", str(exc)) from exc


def service(
    ctx: Context,
    *,
    review: bool,
    spec: SandboxSpec | None = None,
    scratch: Path | None = None,
    prepare_runtime: bool = True,
) -> tuple[CertificationRunner, FingerprintInputs]:
    from factory.agent.certification_probes import (
        CertificationProbeDriver,
        CertificationSandboxExecution,
    )
    from factory.sandbox.sbx import SbxAdapter
    from factory.steps.review import _review_scratch, _review_spec
    from factory.steps.sandbox import build_spec

    trusted = authority.current(ctx)
    snapshot = ctx.store.runtime.policy(ctx.run.id)
    if trusted is None or snapshot is None or ".codex/hooks.json" not in snapshot["files"]:
        raise Blocked(
            "certification-authority-required",
            "Snapshot trusted runtime wiring before automatic certification",
        )
    scratch = scratch or (
        _review_scratch(ctx)
        if review
        else ctx.clone_mount
        if ctx.project.requires_clone
        else ctx.project.path / ".factory/certification"
    )
    spec = spec or (_review_spec(ctx, scratch) if review else build_spec(ctx))
    writable = tuple(w.path for w in spec.workspaces if not w.readonly)
    settings = ctx.store.runtime.settings("run", ctx.run.id)
    config = configuration(Path(settings.get("certification_config", "")), writable_roots=writable)
    source = Path(config["source"])
    # Hash both the source-owned semantics and the code that observes them. An
    # implementation update must not reuse a report generated by older assertions.
    package = Path(__file__).parent
    implementation = (
        package / "runtime_preparation.py",
        package / "agent/runtime_preparation_worker.py",
        package / "certification_runner.py",
        package / "certification.py",
        package / "sandbox/sbx.py",
        package / "sandbox/base.py",
        package / "agent/certified_command.py",
        package / "certification_fingerprint.py",
        package / "sandbox/certification_observer.py",
        package / "agent/certification_probes.py",
        package / "agent/certification_usage_worker.py",
    )
    hooks = {
        str(ctx.worktree / relative): digest
        for relative, digest in snapshot["files"].items()
        if relative == "harness.config.json"
        or relative.startswith((".codex/", ".agents/vendor/harness/"))
    }
    inputs = FingerprintInputs(
        spec=spec,
        binary=config["binary"],
        workdir=str(ctx.worktree),
        env=ctx.env,
        authority_root=trusted,
        probe_root=source.parent,
        hook_files=hooks,
        usage_scope=config["usage_scope"],
        probe_parameters=config,
        probe_implementation=implementation,
        credential_names=tuple(
            json.loads((trusted / "harness.config.json").read_text())
            .get("hooks", {})
            .get("secretVars", [])
        ),
        acknowledged_credentials=ctx.project.acknowledged_env_credentials,
    )
    certificates = Certifications(
        ctx.store, ctx.home / "state/certifications", writable_roots=writable
    )
    observer = cast(CertificationObserver, ctx.sandbox)
    if not callable(getattr(observer, "observe_certification", None)):
        raise Blocked("certification-observer-unavailable", spec.name)
    if prepare_runtime:
        from factory.runtime_preparation import RuntimePreparation

        RuntimePreparation(ctx.store, ctx.sandbox, ctx.home).ensure(
            ctx.run.id,
            spec=spec,
            workdir=inputs.workdir,
            env=inputs.env,
            model=config["model"],
            observe=partial(observe, observer, inputs),
        )
    driver = CertificationProbeDriver(
        certificates,
        cast(SbxAdapter, ctx.sandbox),
        protocol_root=scratch / ctx.run.id,
        workdir=str(ctx.worktree),
        env=ctx.env,
        source=source,
        model=config["model"],
        effort=config["effort"],
        readonly=review,
        alternate_model=config["alternate_model"],
        canary_path=config["canary_path"],
        readonly_root=str(ctx.project.path) if review else None,
    )
    runner = CertificationRunner(
        certificates,
        AgentLaunches(
            ctx.store,
            CertificationSandboxExecution(cast(SbxAdapter, ctx.sandbox), certificates.root),
        ),
        driver,
        partial(observe, observer, inputs),
        home=ctx.home,
        usd_limit=ctx.routing.usd_per_run,
        max_attempts=ctx.registry.defaults.max_total_attempts,
    )
    return runner, inputs


def select(ctx: Context, *, review: bool, baselines: dict[str, dict[str, int]]) -> None:
    runner, inputs = service(ctx, review=review)
    job = runner.ensure(ctx.run.id, automatic=True)
    key = "certification:review" if review else "certification:build"
    ctx.store.runtime.configure("run", ctx.run.id, {key: job["id"]})
    if job["status"] != "passed":
        job = runner.advance(job["id"], now=time.time())
    if job["status"] in {"failed", "cancelled"}:
        raise Blocked("certification-" + job["status"], job.get("failure") or job["id"])
    if job["status"] != "passed":
        raise ProjectQueued("waiting for sandbox certification " + job["id"])
    # Fresh observation is supplied by the controller, never reconstructed from job data.
    current = runner.observe()
    runner.certifications.validate(job["id"], current)
    ctx.agent = AppServerAdapter(
        runner.certifications.root / job["id"] / "compatibility.json",
        runtime_version=current.runtime_version,
        sandbox=inputs.spec.name,
        baselines=baselines,
        immutable=True,
    )


def validate_prepared(ctx: Context, report: Any, *, review: bool) -> dict[str, Any]:
    """Recheck a frozen launch's attestation without scheduling replacement probes.

    A new certificate cannot authorize a request frozen against the old identity.
    Stale preparations require explicit recovery, not paid certification on resume.
    """
    if not isinstance(report, dict) or not isinstance(report.get("certification"), dict):
        raise Blocked("certification-preparation-invalid", "Missing prepared attestation")
    job_id = report["certification"].get("job_id")
    if not isinstance(job_id, str):
        raise Blocked("certification-preparation-invalid", "Missing prepared job identity")
    runner, _ = service(ctx, review=review, prepare_runtime=False)
    job = runner.status(job_id)
    if job["run_id"] != ctx.run.id:
        raise Blocked("certification-preparation-invalid", "Attestation belongs to another run")
    return runner.certifications.validate(job_id, runner.observe())


def freeze_script(script: str, inputs: tuple[Path, ...]) -> str:
    """Retain executable/request bytes in argv, outside candidate-writable staging.

    Compression keeps the single argument below Linux's argument limit for ordinary
    prompts. Oversized requests fail before admission, never fall back to file execution.
    """
    import shlex

    from factory.agent.certified_command import command as certified_command

    requests = [path for path in inputs if path.name.endswith(".app-server.json")]
    if len(requests) != 1:
        raise Blocked("certification-request-invalid", "Expected one staged app-server request")
    path = requests[0]
    request = json.loads(path.read_text())
    frozen = certified_command(
        request,
        prompt=Path(request["prompt"]).read_text(),
        schema=Path(request["schema"]).read_text(),
    )
    command = shlex.join(
        ["/usr/bin/python3", "-I", "-S", str(path.parent / "app_server_worker.py"), str(path)]
    )
    replacement = shlex.join(frozen)
    if "setsid --wait /bin/sh -c " in script:
        # Both commands are inside the envelope's single-quoted inner body.
        command = command.replace("'", "'\"'\"'")
        replacement = replacement.replace("'", "'\"'\"'")
    if script.count(command) != 1:
        raise Blocked(
            "certification-command-invalid", "Staged worker command does not match request"
        )
    return script.replace(command, replacement)
