#!/usr/bin/env python3
"""Keep `.agents/plans/software-factory-plan.md` a verbatim copy of the canonical plan.

`/SOFTWARE-FACTORY-PLAN.md` is the authority. The copy exists only so that agents and tools
which can read files under `.agents/` but not the repository root — or which cannot open the
published artifact — get the same words.

**Why a generator rather than a hand-made copy.** The previous file at that path was a
*condensed* 169k rewrite. It said almost the same thing in slightly different words, so a
reader could not tell it was stale, and it misled two sessions before being deleted in
`9e33944`. The failure was not that a copy existed; it was that the copy could diverge in
*content* and nothing could detect it. A byte-for-byte copy can only diverge in *age*, and
age is checkable — which is what `--check` and the `doctor` row do.

This is the same argument as `harness`'s `vendor_sync.py`, applied to one file.

Stdlib only, and no arguments needed for the common case:

    python3 scripts/sync_plan_copy.py           # regenerate the copy
    python3 scripts/sync_plan_copy.py --check   # exit 1 if the copy is stale
"""

from __future__ import annotations

import argparse
import hashlib
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CANONICAL = ROOT / "SOFTWARE-FACTORY-PLAN.md"
COPY = ROOT / ".agents" / "plans" / "software-factory-plan.md"

#: What separates the generated header from the copied body. The body is everything after
#: the first occurrence, so the header may grow without breaking the comparison.
DELIMITER = "\n---\n\n"


def canonical_text() -> str:
    return CANONICAL.read_text(encoding="utf-8")


def copied_body(text: str) -> str | None:
    """The body of an existing copy, or None when it carries no header delimiter."""
    marker = text.find(DELIMITER)
    if marker == -1:
        return None
    return text[marker + len(DELIMITER) :]


def _commit() -> str:
    try:
        done = subprocess.run(  # noqa: S603 - a fixed argv; `git` from PATH is the point
            ["git", "-C", str(ROOT), "rev-parse", "--short", "HEAD"],  # noqa: S607
            capture_output=True,
            text=True,
            check=False,
            timeout=30,
        )
    except (OSError, subprocess.TimeoutExpired):
        return "unknown"
    return done.stdout.strip() or "unknown"


def render(body: str) -> str:
    digest = hashlib.sha256(body.encode("utf-8")).hexdigest()
    return f"""<!-- GENERATED COPY — DO NOT EDIT THIS FILE -->

> **This is a verbatim copy of `/SOFTWARE-FACTORY-PLAN.md`, which is the authority.**
>
> It exists for agents and tools that can only read files under `.agents/`. Every word below
> the rule is copied byte for byte from the canonical file; nothing is summarised, condensed
> or reordered, and that is deliberate. The previous copy at this path was a *condensed*
> 169k rewrite, and because it said almost the same thing in slightly different words it
> misled two sessions before being deleted in `9e33944`. A copy that can drift in content is
> worse than no copy; a copy that can only drift in *age* can be checked.
>
> | | |
> | --- | --- |
> | source | `/SOFTWARE-FACTORY-PLAN.md` |
> | body sha256 | `{digest}` |
> | copied at | commit `{_commit()}` |
>
> **If you are editing the plan, edit the canonical file and regenerate this one.** From the
> repository root:
>
> ```
> python3 scripts/sync_plan_copy.py
> ```
>
> `scripts/sync_plan_copy.py --check` exits non-zero when this copy has fallen behind, and
> `factory doctor` runs that check.
{DELIMITER.rstrip(chr(10))}

{body}"""


def check() -> tuple[bool, str]:
    """`(ok, detail)` — is the copy still the canonical text?"""
    if not CANONICAL.exists():
        return False, f"{CANONICAL} is missing"
    if not COPY.exists():
        return False, f"{COPY.relative_to(ROOT)} is missing; run scripts/sync_plan_copy.py"
    body = copied_body(COPY.read_text(encoding="utf-8"))
    if body is None:
        return False, f"{COPY.relative_to(ROOT)} has no generated header; regenerate it"
    if body != canonical_text():
        return False, (
            f"{COPY.relative_to(ROOT)} has fallen behind SOFTWARE-FACTORY-PLAN.md; "
            "run scripts/sync_plan_copy.py"
        )
    return True, f"{len(body)} bytes, identical to the canonical plan"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check", action="store_true", help="report whether the copy is current; write nothing"
    )
    args = parser.parse_args()

    if args.check:
        ok, detail = check()
        print(("OK: " if ok else "STALE: ") + detail)
        return 0 if ok else 1

    COPY.parent.mkdir(parents=True, exist_ok=True)
    COPY.write_text(render(canonical_text()), encoding="utf-8")
    print(f"wrote {COPY.relative_to(ROOT)} from SOFTWARE-FACTORY-PLAN.md")
    return 0


if __name__ == "__main__":
    sys.exit(main())
