"""§21.1 — registry validation and project resolution."""

from __future__ import annotations

from pathlib import Path

import pytest

from factory.machine import Blocked
from factory.registry import RegistryError, load_registry

HOME = Path(__file__).resolve().parents[2]

TWO_TEAMS = """
[vault]
path = "/tmp/vault"

[projects.one]
team = "BAC"
path = "/tmp/one"
remote = "https://example.invalid/one.git"
base_branch = "v2"
stack = "python"
build_sandbox = "factory-build-one"

[projects.two]
team = "BAC"
path = "/tmp/two"
remote = "https://example.invalid/two.git"
base_branch = "v2"
stack = "python"
build_sandbox = "factory-build-two"
"""

MAIN_AS_BASE = """
[vault]
path = "/tmp/vault"

[projects.python-harness]
team = "BAC"
path = "/tmp/one"
remote = "https://example.invalid/one.git"
base_branch = "main"
stack = "python"
build_sandbox = "factory-build-python-harness"
"""


def test_the_shipped_registry_loads() -> None:
    registry = load_registry(HOME / "config" / "projects.toml")
    assert set(registry.projects) == {"nemoclaw-dev", "frontend-harness"}
    assert registry.projects["nemoclaw-dev"].base_ref == "origin/james/feat/prototype"


def test_two_projects_claiming_one_team_refuse_to_load(tmp_path: Path) -> None:
    path = tmp_path / "projects.toml"
    path.write_text(TWO_TEAMS)
    with pytest.raises(RegistryError, match="claimed by both"):
        load_registry(path)


def test_main_is_refused_as_a_base_branch_for_the_harness_repos(tmp_path: Path) -> None:
    # `main` there is generated by generate-main.yml; a PR against it would be
    # overwritten by the next push to v2.
    path = tmp_path / "projects.toml"
    path.write_text(MAIN_AS_BASE)
    with pytest.raises(RegistryError, match="generated"):
        load_registry(path)


def test_unknown_team_is_not_eligible_rather_than_an_error() -> None:
    registry = load_registry(HOME / "config" / "projects.toml")
    with pytest.raises(Blocked) as caught:
        registry.resolve("ZZZ-1")
    assert caught.value.reason == "unknown-team"


def test_resolution_uses_the_identifier_prefix() -> None:
    registry = load_registry(HOME / "config" / "projects.toml")
    # BAC was python-harness's until 2026-08-31; the retired block is commented out in
    # `projects.toml` and the team key handed over, because two projects cannot claim one.
    assert registry.resolve("BAC-4").name == "nemoclaw-dev"
    assert registry.resolve("FRO-7").name == "frontend-harness"


def test_python_project_carries_the_measured_uv_environment_fix() -> None:
    # p0-3: a sandbox `uv sync` against the bind-mounted workspace destroyed the host
    # venv. This env var is the measured mitigation, so its absence is a regression.
    project = load_registry(HOME / "config" / "projects.toml").projects["nemoclaw-dev"]
    assert project.env["UV_PROJECT_ENVIRONMENT"].startswith("/home/agent/")


def test_the_shipped_registry_denies_the_mcp_gateway_endpoint() -> None:
    # §8.7's compensating control for `mcpgateway`, which `sbx` uploads into every
    # sandbox and which no per-sandbox flag can remove. Losing this row would leave the
    # narrowed secret check with nothing behind it.
    registry = load_registry(HOME / "config" / "projects.toml")
    assert "mcp.linear.app" in registry.defaults.deny_network


def test_deny_network_defaults_to_nothing_rather_than_to_a_guess(tmp_path: Path) -> None:
    # A registry that invented deny rules on its own would be a registry whose sandbox
    # specification does not match what is written down.
    path = tmp_path / "projects.toml"
    path.write_text(
        TWO_TEAMS.replace('team = "BAC"\npath = "/tmp/two"', 'team = "FRO"\npath = "/tmp/two"')
    )
    assert load_registry(path).defaults.deny_network == ()


SENSITIVE = """
[vault]
path = "/tmp/vault"

[projects.declared]
team = "AAA"
path = "/tmp/declared"
remote = "https://example.invalid/a.git"
base_branch = "v2"
stack = "python"
build_sandbox = "factory-build-a"
sensitive_paths = ["src/app/ai/**", "src/app/core/**"]

[projects.silent]
team = "BBB"
path = "/tmp/silent"
remote = "https://example.invalid/b.git"
base_branch = "v2"
stack = "monorepo"
build_sandbox = "factory-build-b"
"""


def test_sensitive_paths_are_read_from_the_registry(tmp_path: Path) -> None:
    # §15.2's Tier-2 sensitive-path trigger is a stack fact, and §3.2 gives layer D none of
    # those. It lived in a dict in `steps/review.py` until 2026-08-23, where the frontend
    # entry named a directory that has never existed in the repository it described.
    config = tmp_path / "projects.toml"
    config.write_text(SENSITIVE)

    registry = load_registry(config)

    assert registry.projects["declared"].sensitive_paths == ("src/app/ai/**", "src/app/core/**")


def test_a_project_that_declares_no_sensitive_paths_gets_an_empty_tuple(tmp_path: Path) -> None:
    # Empty is a real answer: the size and protected-path triggers still apply, and a
    # project is not obliged to nominate directories. It must not be a parse error, and it
    # must not fall back to some other project's list.
    config = tmp_path / "projects.toml"
    config.write_text(SENSITIVE)

    registry = load_registry(config)

    assert registry.projects["silent"].sensitive_paths == ()


def test_the_real_registry_declares_sensitive_paths_that_match_something() -> None:
    # The regression this whole change exists for. `doctor` runs the same check against the
    # working copies; this one asserts the far cheaper half — that the globs are at least
    # well-formed and non-empty for the two projects that declare them — without needing
    # either repository to be checked out.
    registry = load_registry(HOME / "config" / "projects.toml")

    for project in registry.projects.values():
        for glob in project.sensitive_paths:
            assert glob.endswith("/**"), f"{project.name}: {glob} is not a directory glob"
            assert not glob.startswith("/"), f"{project.name}: {glob} is not repo-relative"


# --------------------------------------------------------------------------------
# the forge key — §13.2
# --------------------------------------------------------------------------------


def test_a_project_that_omits_the_forge_key_still_delivers_to_github() -> None:
    # Every project predating the GitLab adapter omits the key, and the delivery path must
    # not change under them. A default that had to be written out in `projects.toml` would
    # have made this a migration.
    registry = load_registry(HOME / "config" / "projects.toml")

    assert registry.projects["frontend-harness"].forge == "github"


def test_the_shipped_registry_routes_nemoclaw_to_gitlab() -> None:
    # The first non-GitHub project. Pinned because `forge` decides which CLI's keyring
    # credential a push authenticates with, and a silent revert to the default would push
    # to a GitHub remote that does not exist rather than failing.
    registry = load_registry(HOME / "config" / "projects.toml")

    assert registry.projects["nemoclaw-dev"].forge == "gitlab"
    assert registry.projects["nemoclaw-dev"].remote.startswith("git@172.18.194.183:")


def test_a_project_can_name_gitlab(tmp_path: Path) -> None:
    config = tmp_path / "projects.toml"
    config.write_text(
        SENSITIVE.replace('stack = "monorepo"', 'stack = "monorepo"\nforge = "gitlab"')
    )

    assert load_registry(config).projects["silent"].forge == "gitlab"


def test_an_unknown_forge_is_a_load_error_not_a_delivery_error(tmp_path: Path) -> None:
    # The point of validating here: a typo'd forge must fail when James edits the registry,
    # not eight minutes into a run that has already spent model budget on an implement step.
    config = tmp_path / "projects.toml"
    config.write_text(
        SENSITIVE.replace('stack = "monorepo"', 'stack = "monorepo"\nforge = "githib"')
    )

    with pytest.raises(RegistryError, match="names forge 'githib'"):
        load_registry(config)


def test_the_registry_and_the_dispatch_agree_on_the_forge_names() -> None:
    """`registry._FORGES` is spelled out rather than imported, to avoid a cycle.

    That duplication is only safe while something fails when the two drift, which is this.
    """
    from factory.delivery.forge import FORGES
    from factory.registry import _FORGES

    assert set(_FORGES) == set(FORGES)
