"""§21.1 — registry validation and project resolution."""

from __future__ import annotations

import re
from pathlib import Path

import pytest

from factory.machine import Blocked
from factory.registry import RegistryError, load_registry

HOME = Path(__file__).resolve().parents[2]
#: The parser tests read this synthetic registry. Only the `test_the_shipped_registry_*`
#: guards read `config/projects.toml`, and each asserts a policy every project must meet,
#: so retiring a project never fails a test.
EXAMPLE = HOME / "tests/fixtures/registry/projects.toml"
SHIPPED = HOME / "config/projects.toml"

TWO_TEAMS = """
[vault]
path = "/tmp/vault"

[projects.one]
team = "BAC"
path = "/tmp/one"
remote = "https://example.invalid/one.git"
base_branch = "v2"
stack = "python"
build_sandbox = "factory-build-one"

[projects.two]
team = "BAC"
path = "/tmp/two"
remote = "https://example.invalid/two.git"
base_branch = "v2"
stack = "python"
build_sandbox = "factory-build-two"
"""

MAIN_AS_BASE = """
[vault]
path = "/tmp/vault"

[projects.python-harness]
team = "BAC"
path = "/tmp/one"
remote = "https://example.invalid/one.git"
base_branch = "main"
stack = "python"
build_sandbox = "factory-build-python-harness"
"""


def test_the_example_registry_loads() -> None:
    registry = load_registry(EXAMPLE)
    assert set(registry.projects) == {"gitlab-app", "github-app"}
    assert registry.projects["gitlab-app"].base_ref == "origin/example-branch"


def test_two_projects_claiming_one_team_refuse_to_load(tmp_path: Path) -> None:
    path = tmp_path / "projects.toml"
    path.write_text(TWO_TEAMS)
    with pytest.raises(RegistryError, match="claimed by both"):
        load_registry(path)


def test_main_is_refused_as_a_base_branch_for_the_harness_repos(tmp_path: Path) -> None:
    # `main` there is generated by generate-main.yml; a PR against it would be
    # overwritten by the next push to v2.
    path = tmp_path / "projects.toml"
    path.write_text(MAIN_AS_BASE)
    with pytest.raises(RegistryError, match="generated"):
        load_registry(path)


def test_unknown_team_is_not_eligible_rather_than_an_error() -> None:
    registry = load_registry(EXAMPLE)
    with pytest.raises(Blocked) as caught:
        registry.resolve("ZZZ-1")
    assert caught.value.reason == "unknown-team"


def test_resolution_uses_the_identifier_prefix() -> None:
    registry = load_registry(EXAMPLE)
    assert registry.resolve("GLA-4").name == "gitlab-app"
    assert registry.resolve("GHA-7").name == "github-app"


def test_the_shipped_registry_gives_every_python_project_the_uv_environment_fix() -> None:
    # p0-3: a sandbox `uv sync` against the bind-mounted workspace destroyed the host
    # venv. This env var is the measured mitigation, so its absence is a regression. Two
    # writers share one build VM, so above one writer the path must also be per run.
    registry = load_registry(SHIPPED)
    for project in registry.projects.values():
        if project.stack == "python":
            uv_env = project.env["UV_PROJECT_ENVIRONMENT"]
            assert uv_env.startswith("/home/agent/"), project.name
            if registry.concurrency_for(project) > 1:
                assert "{run}" in uv_env, project.name


def test_the_shipped_registry_denies_the_mcp_gateway_endpoint() -> None:
    # §8.7's compensating control for `mcpgateway`, which `sbx` uploads into every
    # sandbox and which no per-sandbox flag can remove. Losing this row would leave the
    # narrowed secret check with nothing behind it.
    registry = load_registry(SHIPPED)
    assert "mcp.linear.app" in registry.defaults.deny_network


def test_deny_network_defaults_to_nothing_rather_than_to_a_guess(tmp_path: Path) -> None:
    # A registry that invented deny rules on its own would be a registry whose sandbox
    # specification does not match what is written down.
    path = tmp_path / "projects.toml"
    path.write_text(
        TWO_TEAMS.replace('team = "BAC"\npath = "/tmp/two"', 'team = "FRO"\npath = "/tmp/two"')
    )
    assert load_registry(path).defaults.deny_network == ()


SENSITIVE = """
[vault]
path = "/tmp/vault"

[projects.declared]
team = "AAA"
path = "/tmp/declared"
remote = "https://example.invalid/a.git"
base_branch = "v2"
stack = "python"
build_sandbox = "factory-build-a"
sensitive_paths = ["src/app/ai/**", "src/app/core/**"]

[projects.silent]
team = "BBB"
path = "/tmp/silent"
remote = "https://example.invalid/b.git"
base_branch = "v2"
stack = "monorepo"
build_sandbox = "factory-build-b"
"""


def test_sensitive_paths_are_read_from_the_registry(tmp_path: Path) -> None:
    # §15.2's Tier-2 sensitive-path trigger is a stack fact, and §3.2 gives layer D none of
    # those. It lived in a dict in `steps/review.py` until 2026-08-23, where the frontend
    # entry named a directory that has never existed in the repository it described.
    config = tmp_path / "projects.toml"
    config.write_text(SENSITIVE)

    registry = load_registry(config)

    assert registry.projects["declared"].sensitive_paths == ("src/app/ai/**", "src/app/core/**")


def test_a_project_that_declares_no_sensitive_paths_gets_an_empty_tuple(tmp_path: Path) -> None:
    # Empty is a real answer: the size and protected-path triggers still apply, and a
    # project is not obliged to nominate directories. It must not be a parse error, and it
    # must not fall back to some other project's list.
    config = tmp_path / "projects.toml"
    config.write_text(SENSITIVE)

    registry = load_registry(config)

    assert registry.projects["silent"].sensitive_paths == ()


def test_the_shipped_registry_declares_well_formed_sensitive_paths() -> None:
    # The regression this whole change exists for. `doctor` runs the same check against the
    # working copies; this one asserts the far cheaper half, that the globs are at least
    # well-formed, without needing any repository to be checked out.
    registry = load_registry(SHIPPED)

    for project in registry.projects.values():
        for glob in project.sensitive_paths:
            assert glob.endswith("/**"), f"{project.name}: {glob} is not a directory glob"
            assert not glob.startswith("/"), f"{project.name}: {glob} is not repo-relative"


# --------------------------------------------------------------------------------
# the forge key — §13.2
# --------------------------------------------------------------------------------


def test_a_project_that_omits_the_forge_key_still_delivers_to_github() -> None:
    # Every project predating the GitLab adapter omits the key, and the delivery path must
    # not change under them. A default that had to be written out in `projects.toml` would
    # have made this a migration.
    registry = load_registry(EXAMPLE)

    assert registry.projects["github-app"].forge == "github"


def test_the_shipped_registry_names_a_forge_for_every_non_github_remote() -> None:
    # `forge` decides which CLI's keyring credential a push authenticates with, and a
    # silent revert to the default would push to a GitHub remote that does not exist
    # rather than failing.
    for project in load_registry(SHIPPED).projects.values():
        if project.forge == "github":
            assert re.match(r"(https://|git@)github\.com[/:]", project.remote), project.name


def test_a_project_can_name_gitlab(tmp_path: Path) -> None:
    config = tmp_path / "projects.toml"
    config.write_text(
        SENSITIVE.replace('stack = "monorepo"', 'stack = "monorepo"\nforge = "gitlab"')
    )

    assert load_registry(config).projects["silent"].forge == "gitlab"


def test_an_unknown_forge_is_a_load_error_not_a_delivery_error(tmp_path: Path) -> None:
    # The point of validating here: a typo'd forge must fail when James edits the registry,
    # not eight minutes into a run that has already spent model budget on an implement step.
    config = tmp_path / "projects.toml"
    config.write_text(
        SENSITIVE.replace('stack = "monorepo"', 'stack = "monorepo"\nforge = "githib"')
    )

    with pytest.raises(RegistryError, match="names forge 'githib'"):
        load_registry(config)


def test_the_registry_and_the_dispatch_agree_on_the_forge_names() -> None:
    """`registry._FORGES` is spelled out rather than imported, to avoid a cycle.

    That duplication is only safe while something fails when the two drift, which is this.
    """
    from factory.delivery.forge import FORGES
    from factory.registry import _FORGES

    assert set(_FORGES) == set(FORGES)


SANDBOX_DELIVERY = """
[vault]
path = "/tmp/vault"

[projects.one]
team = "BAC"
path = "/tmp/one"
remote = "git@example.invalid:g/one.git"
base_branch = "v2"
stack = "python"
forge = "gitlab"
build_sandbox = "factory-build-one"
{extra}

[projects.one.sandbox_delivery]
{table}
"""

_FULL_TABLE = """
api_url = "https://10.0.0.1/"
project_path = "/g/sub/one/"
placeholder_env = "FACTORY_GITLAB_TOKEN"
"""


def _sandbox_delivery(tmp_path: Path, *, table: str = _FULL_TABLE, extra: str = "") -> Path:
    path = tmp_path / "projects.toml"
    path.write_text(SANDBOX_DELIVERY.format(table=table, extra=extra))
    return path


def test_sandbox_delivery_is_absent_for_every_project_that_does_not_declare_it() -> None:
    registry = load_registry(EXAMPLE)
    assert registry.projects["github-app"].sandbox_delivery is None
    declared = registry.projects["gitlab-app"].sandbox_delivery
    assert declared is not None
    assert declared.placeholder_env == "FACTORY_GITLAB_TOKEN"


def test_the_shipped_registry_grants_in_vm_delivery_to_no_new_project() -> None:
    """The strong default, asserted on the shipped file rather than on a fixture.

    `None` is what keeps §13.2 true: `forge.for_delivery` returns the host adapter and
    `policy.capability_secrets` admits nothing. A project acquiring this table by accident
    would be a boundary change with no diff in `src/`, so a new one has to be named here.
    """
    registry = load_registry(SHIPPED)
    declared = {p.name for p in registry.projects.values() if p.sandbox_delivery is not None}
    assert declared <= {"nemoclaw-dev"}


def test_the_sandbox_delivery_table_is_normalised(tmp_path: Path) -> None:
    # A trailing slash on `api_url` and a leading one on `project_path` both produce a
    # URL with `//` in it, which GitLab answers with a redirect that curl does not follow
    # — a 301 with an empty body, reported as "returned no web_url".
    declared = load_registry(_sandbox_delivery(tmp_path)).projects["one"].sandbox_delivery
    assert declared is not None
    assert declared.api_url == "https://10.0.0.1"
    assert declared.project_path == "g/sub/one"


def test_a_github_project_cannot_declare_in_vm_delivery(tmp_path: Path) -> None:
    # `sandbox_gitlab.py` is the only in-VM adapter. A github project carrying this table
    # would deliver host-side and look, in the registry, as though it did not.
    path = tmp_path / "projects.toml"
    path.write_text(
        SANDBOX_DELIVERY.format(table=_FULL_TABLE, extra="").replace(
            'forge = "gitlab"', 'forge = "github"'
        )
    )
    with pytest.raises(RegistryError, match="only for gitlab"):
        load_registry(path)


def test_a_clone_project_cannot_declare_in_vm_delivery(tmp_path: Path) -> None:
    # The branch a clone run builds lives in the VM's private clone, not in the worktree
    # this adapter pushes from: the combination pushes nothing and reports success.
    with pytest.raises(RegistryError, match="requires_clone"):
        load_registry(_sandbox_delivery(tmp_path, extra="requires_clone = true"))


@pytest.mark.parametrize("missing", ["api_url", "project_path", "placeholder_env"])
def test_a_half_specified_sandbox_delivery_table_refuses_to_load(
    tmp_path: Path, missing: str
) -> None:
    """Validated at load, not at delivery. Delivery is the *last* step of a run: a table
    that is discovered to be incomplete there has already spent the whole model budget."""
    table = "\n".join(
        line for line in _FULL_TABLE.strip().splitlines() if not line.startswith(missing)
    )
    with pytest.raises(RegistryError, match=missing):
        load_registry(_sandbox_delivery(tmp_path, table=table))


# --------------------------------------------------------------------------------
# §11.3's writer limit, per project
# --------------------------------------------------------------------------------

CONCURRENCY = """
[vault]
path = "/tmp/vault"

[defaults]
concurrency_per_project = 1

[projects.raised]
team = "AAA"
path = "/tmp/raised"
remote = "https://example.invalid/a.git"
base_branch = "v2"
stack = "python"
build_sandbox = "factory-build-a"
concurrency_per_project = 3

[projects.silent]
team = "BBB"
path = "/tmp/silent"
remote = "https://example.invalid/b.git"
base_branch = "v2"
stack = "python"
build_sandbox = "factory-build-b"
"""


def test_a_project_can_raise_its_own_writer_limit(tmp_path: Path) -> None:
    # How many writers a repository can carry is a fact about that repository, so the
    # raise belongs to the project and not to every project at once.
    path = tmp_path / "projects.toml"
    path.write_text(CONCURRENCY)
    registry = load_registry(path)
    assert registry.concurrency_for(registry.projects["raised"]) == 3


def test_a_project_that_says_nothing_falls_back_to_the_defaults(tmp_path: Path) -> None:
    # The fallback is the whole point of the field being optional: raising the floor for
    # everything stays one edit in `[defaults]`.
    path = tmp_path / "projects.toml"
    path.write_text(CONCURRENCY)
    registry = load_registry(path)
    silent = registry.projects["silent"]
    assert silent.concurrency_per_project is None
    assert registry.concurrency_for(silent) == 1
    assert registry.concurrency_for(silent) == registry.defaults.concurrency_per_project


def test_the_defaults_move_the_projects_that_did_not_decide(tmp_path: Path) -> None:
    path = tmp_path / "projects.toml"
    path.write_text(
        CONCURRENCY.replace("concurrency_per_project = 1", "concurrency_per_project = 2")
    )
    registry = load_registry(path)
    assert registry.concurrency_for(registry.projects["silent"]) == 2
    assert registry.concurrency_for(registry.projects["raised"]) == 3  # its own answer stands


def test_an_env_that_would_override_the_agent_cli_refuses_to_load(tmp_path: Path) -> None:
    # `CLAUDE_CODE_EFFORT_LEVEL` beats `--effort` and `ANTHROPIC_API_KEY` beats the login,
    # so a project that sets either would run on something routing never chose.
    body = (
        MAIN_AS_BASE.replace('base_branch = "main"', 'base_branch = "v2"')
        + '\n[projects.python-harness.env]\nCLAUDE_CODE_EFFORT_LEVEL = "max"\n'
    )
    path = tmp_path / "projects.toml"
    path.write_text(body)
    with pytest.raises(RegistryError, match="CLAUDE_CODE_EFFORT_LEVEL"):
        load_registry(path)


def test_a_zero_writer_limit_refuses_to_load(tmp_path: Path) -> None:
    # Zero is not "paused", it is a project that can never be claimed and says nothing
    # about why — the failure a poller would report once per tick, forever.
    path = tmp_path / "projects.toml"
    path.write_text(
        CONCURRENCY.replace("concurrency_per_project = 3", "concurrency_per_project = 0")
    )
    with pytest.raises(RegistryError, match="unclaimable"):
        load_registry(path)


def test_a_project_raise_and_the_default_both_reach_concurrency_for() -> None:
    registry = load_registry(EXAMPLE)
    assert registry.concurrency_for(registry.projects["gitlab-app"]) == 2
    assert registry.concurrency_for(registry.projects["github-app"]) == 1
