"""§21.1 — registry validation and project resolution."""

from __future__ import annotations

from pathlib import Path

import pytest

from factory.machine import Blocked
from factory.registry import RegistryError, load_registry

HOME = Path(__file__).resolve().parents[2]

TWO_TEAMS = """
[vault]
path = "/tmp/vault"

[projects.one]
team = "BAC"
path = "/tmp/one"
remote = "https://example.invalid/one.git"
base_branch = "v2"
stack = "python"
build_sandbox = "factory-build-one"

[projects.two]
team = "BAC"
path = "/tmp/two"
remote = "https://example.invalid/two.git"
base_branch = "v2"
stack = "python"
build_sandbox = "factory-build-two"
"""

MAIN_AS_BASE = """
[vault]
path = "/tmp/vault"

[projects.python-harness]
team = "BAC"
path = "/tmp/one"
remote = "https://example.invalid/one.git"
base_branch = "main"
stack = "python"
build_sandbox = "factory-build-python-harness"
"""


def test_the_shipped_registry_loads() -> None:
    registry = load_registry(HOME / "config" / "projects.toml")
    assert set(registry.projects) == {"python-harness", "frontend-harness"}
    assert registry.projects["python-harness"].base_ref == "origin/v2"


def test_two_projects_claiming_one_team_refuse_to_load(tmp_path: Path) -> None:
    path = tmp_path / "projects.toml"
    path.write_text(TWO_TEAMS)
    with pytest.raises(RegistryError, match="claimed by both"):
        load_registry(path)


def test_main_is_refused_as_a_base_branch_for_the_harness_repos(tmp_path: Path) -> None:
    # `main` there is generated by generate-main.yml; a PR against it would be
    # overwritten by the next push to v2.
    path = tmp_path / "projects.toml"
    path.write_text(MAIN_AS_BASE)
    with pytest.raises(RegistryError, match="generated"):
        load_registry(path)


def test_unknown_team_is_not_eligible_rather_than_an_error() -> None:
    registry = load_registry(HOME / "config" / "projects.toml")
    with pytest.raises(Blocked) as caught:
        registry.resolve("ZZZ-1")
    assert caught.value.reason == "unknown-team"


def test_resolution_uses_the_identifier_prefix() -> None:
    registry = load_registry(HOME / "config" / "projects.toml")
    assert registry.resolve("BAC-4").name == "python-harness"
    assert registry.resolve("FRO-7").name == "frontend-harness"


def test_python_project_carries_the_measured_uv_environment_fix() -> None:
    # p0-3: a sandbox `uv sync` against the bind-mounted workspace destroyed the host
    # venv. This env var is the measured mitigation, so its absence is a regression.
    project = load_registry(HOME / "config" / "projects.toml").projects["python-harness"]
    assert project.env["UV_PROJECT_ENVIRONMENT"].startswith("/home/agent/")
